# 配置文件

# 应用名称
name = "BroQiang 博客"

# 应用的域名，静态资源等会用到此配置
url = "http://localhost"

# 应用监听地址，为空最终会是 0.0.0.0 ，如果不清楚配置什么就留空即可
host = ""

# 应用端口
port = 8080

# 是否开启 debug， 生产环境要设置成 false， 是否开启 debug
# 会影响到 gin 的模式和日志的记录方式
debug = true

# markdown 文档的保存目录
markdown_dir = "resources/blog-docs"

# icp 备案信息
icp = "京ICP备17034182号"

# 百度统计的 key ，如果不使用的话，不配置或使用空字符串即可
tongji = "ceb4dafbd34d908306d9745fc0e0f4e4"

# 日志相关的配置
[log]
    # 日志保存位置，默认是应用根目录下生成日志文件
    # 如果以 / 开始，就是使用绝对路径，如： /logs
    # 如果不是以 / 开始的目录，如 logs ， 会自动放在应用根目录下创建 $appPath/logs
    dir = "logs"

    # 日志格式， 适配的 time.Format 的格式
    # 如果为空就会定义一个默认的格式 "2006-01/02"
    format = ""

    # 日志模式，共有三种
    # close 关闭, 如果关闭将不会再写日志
    # file 写入文件，会写入到上面的 log_dir 配置的目录中
    # stdout 写入到标准输入，一般就是终端直接打印日志，建议 debug 的时候配置
    mode = "file"

    # 是否记录访问日志，就是浏览器访问系统时产生的日志，
    # 只有上面的 mode 不为 close， 并且 access 为 true 的时候才会记录日志
    access = true

